version: '3.8'

services:
  jenkins-inbound-agent:
    image: anyssido/jenkins-inbound-docker-agent
    init: true
    privileged: true
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME}
      - JENKINS_SECRET=${JENKINS_SECRET}
      - JENKINS_WEB_SOCKET=true
      - TINI_SUBREAPER=true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"